groups:
    - developer
    - media
    - manager
    - speedledger

attributes:
    osxdefaults:
        finder:
            finder_set_preferred_view_style: icnv
        terminal:
            profile: Homebrew
            color_scheme: Homebrew
        computername: PB-HAL-9000

    git:
        name: Pål Brattberg
        email: pb@speedledger.se
    authorization:
        sudo:
            users:
                - pal
            passwordless: true
            include_sudoers_d: true
