attributes:
    homebrewalt:
        apps:
        cask_apps:
            - spotify   # Play that funky music, white boy!
            - hipchat   # Management by chat
            - skype     # Skype for recruiting
            - evernote  # Da notes, da notes, da notes be on fire!
            - alfred    # more stylish than spotlight
            - dropbox   # Files, files baby
            - google-drive  # Files, files maybe
            - microsoft-office # The ultimate tool for MANAGER
            - paparazzi # Get those screen shots
