attributes:
    homebrewalt:
        apps:
            - auto-scaling
            - aws-cfn-tools
            - aws-elasticache
            - aws-elasticbeanstalk
            - aws-iam-tools
            - aws-sns-cli
            - cloud-watch
            - ec2-ami-tools
            - ec2-api-tools
            - elb-tools
            - rds-command-line-tools
